name: DocumentationChatFriend.Backend Docker Image CI

on:
  push:
    branches:
      - "master"
    paths:
      - "Backend/**"
  pull_request:
    branches:
      - "master"
    paths:
      - "Backend/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

        # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./DocumentationChatFriend.sln
      # Build the solution
      - name: Build solution
        run: dotnet build ./DocumentationChatFriend.sln --no-restore --configuration Release

      # Run tests
      - name: Run tests
        run: dotnet test ./DocumentationChatFriend.sln --no-build --configuration Release --logger trx

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build ./Backend/src --file ./Backend/src/Dockerfile --tag josephrashidmaalouf/documentation-chat-friend-backend:${{ github.run_id }} --tag josephrashidmaalouf/documentation-chat-friend-backend:latest

      # Push both the latest and run-id tagged images
      - name: Push Docker images
        run: |
          docker push josephrashidmaalouf/documentation-chat-friend-backend:latest
          docker push josephrashidmaalouf/documentation-chat-friend-backend:${{ github.run_id }}
